# Generated by Django 5.0.2 on 2025-11-06 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publicacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("SOC", "Social"),
                            ("CUL", "Cultural"),
                            ("DEP", "Deportivo"),
                            ("ACA", "Académico"),
                            ("OTR", "Otro"),
                        ],
                        default="OTR",
                        max_length=50,
                    ),
                ),
                (
                    "privacidad",
                    models.CharField(
                        choices=[
                            ("PUB", "Público"),
                            ("PRI", "Privado"),
                            ("AMI", "Amigos"),
                        ],
                        default="PUB",
                        max_length=50,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("VIG", "Vigente"),
                            ("FIN", "Finalizado"),
                            ("CAN", "Cancelado"),
                        ],
                        default="VIG",
                        max_length=50,
                    ),
                ),
                ("terminos_condiciones", models.TextField()),
                ("capacidad_maxima", models.IntegerField()),
                ("fecha_evento", models.DateTimeField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("me_gusta", models.IntegerField(default=0)),
                ("comentarios", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre_usuario", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("O", "Otro"),
                            ("N", "Prefiero no decirlo"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "foto_perfil",
                    models.ImageField(blank=True, null=True, upload_to="fotos_perfil/"),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("biografia", models.TextField(blank=True)),
                ("latitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("ciudad", models.CharField(max_length=100)),
                ("pais", models.CharField(max_length=100)),
                ("tema_prefefrido", models.CharField(blank=True, max_length=100)),
                ("verificado", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImagenPublicacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("imagen", models.ImageField(upload_to="publicaciones/")),
                (
                    "publicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="api.publicacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UbicacionEvento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("latitud", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitud", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="publicacion",
            name="id_usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.usuario"
            ),
        ),
        migrations.CreateModel(
            name="ActividadeAgenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("fecha_activiad", models.DateField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.usuario"
                    ),
                ),
            ],
        ),
    ]
