# Generated by Django 5.1.1 on 2025-11-06 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_usuario_ciudad_alter_usuario_latitud_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inscripcion", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEND", "Pendiente"),
                            ("CONF", "Confirmada"),
                            ("CANC", "Cancelada"),
                        ],
                        default="PEND",
                        max_length=4,
                    ),
                ),
                (
                    "publicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.publicacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.usuario"
                    ),
                ),
            ],
        ),
    ]
