# Generated by Django 5.2.8 on 2025-11-11 17:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_usuario_ciudad_alter_usuario_latitud_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscripciones",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "estado_asistencia",
                    models.CharField(
                        choices=[
                            ("INS", "Inscrito"),
                            ("ASI", "Asisticio"),
                            ("NOASI", "No asistio"),
                            ("CAN", "Cancelado"),
                        ],
                        default="INS",
                        max_length=10,
                    ),
                ),
                (
                    "id_publicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.publicacion",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.usuario"
                    ),
                ),
            ],
        ),
    ]
