# Generated by Django 5.2.8 on 2025-11-14 00:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_comentariopublicacion_likepublicacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "remitente",
                    models.CharField(
                        choices=[("usuario", "Usuario"), ("bot", "Bot")], max_length=10
                    ),
                ),
                ("mensaje", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversaciones",
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha"],
            },
        ),
    ]
