# Generated by Django 5.2.8 on 2025-11-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_conversacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[("USUARIO", "Usuario"), ("ADMIN", "Administrador")],
                default="USUARIO",
                max_length=10,
            ),
        ),
    ]
